services:
  web:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - api
    environment:
      - FLASK_API_BASE_URL=http://backend:3000
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=development
